export const feedbacks = [
    {
        name: "Aditi S.",
        branch: "Computer Science",
        star: 5,
        description: "LogicHelp helped me master C++ through its structured courses and interactive coding challenges. The AI bug detection feature is a lifesaver for debugging!",
        company: "Tech Solutions Inc.",
    },
    {
        name: "Sneha P.",
        branch: "Data Science",
        star: 5,
        description: "The Python courses were comprehensive and easy to follow. The community support helped me clarify my doubts promptly.",
        company: "Data Analytics Co.",
    },
    {
        name: "Vikram T.",
        branch: "Information Technology",
        star: 4,
        description: "Participating in hackathons through LogicHelp boosted my confidence and skills. I appreciated the feedback loop from mentors!",
        company: "StartUp Hub",
    },
    {
        name: "Meera L.",
        branch: "Electronics",
        star: 5,
        description: "The projects section allowed me to build a strong portfolio that impressed my future employers. I’m grateful for the resources provided!",
        company: "GadgetCorp",
    },
    {
        name: "Aman P.",
        branch: "Artificial Intelligence",
        star: 4,
        description: "The AI bug detection tool made debugging a breeze, helping me focus on building features instead of getting stuck on errors.",
        company: "AI Innovations",
    },
    {
        name: "Ravi K.",
        branch: "Mechanical Engineering",
        star: 5,
        description: "The challenges provided by LogicHelp are both fun and educational. They pushed me to think critically and solve complex problems.",
        company: "Engineering Pros",
    },
    {
        name: "Neha J.",
        branch: "Information Technology",
        star: 4,
        description: "Thanks to the job placement assistance, I was able to secure a job at a top tech firm right after graduation. Highly recommend this platform!",
        company: "Global Tech",
    },
    {
        name: "Siddharth R.",
        branch: "Computer Science",
        star: 5,
        description: "The interactive courses are fantastic! They made learning Java so much easier than traditional methods.",
        company: "Code Warriors",
    },
    {
        name: "Priya T.",
        branch: "Cybersecurity",
        star: 4,
        description: "The doubt-solving sessions were incredibly helpful. I always received quick and effective answers to my questions.",
        company: "SecureNet",
    },
];

